pipeline {
    agent any

    environment {
        DOCKER_CRED = credentials('docker-hub-guntinue')
        IMAGE_NAME = 'guntinue/armageddon-frontend'
    }

    stages {
        // 노드 의존성 설치 및 빌드
        stage('Build Node.js') {
            steps {
                dir('frontend') {
                    // Node.js가 젠킨스 서버에 설치되어 있어야 함
                    // 없다면 docker agent를 쓰는 방법도 있지만 일단 쉘로 진행
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        // 도커 이미지 빌드
        stage('Docker Build') {
            steps {
                dir('frontend') {
                    // 플랫폼 명시 (Mac M1/M2 사용자를 위해 amd64 강제)
                    sh 'docker build --no-cache --platform linux/amd64 -t $IMAGE_NAME:latest .'
                }
            }
        }

        // 도커 허브 푸시
        stage('Docker Push') {
            steps {
                sh 'echo $DOCKER_CRED_PSW | docker login -u $DOCKER_CRED_USR --password-stdin'
                sh 'docker push $IMAGE_NAME:latest'
            }
        }

        // 배포
        stage('Deploy to K8s') {
            steps {
                // 프론트엔드 파드 삭제 -> 재시작
                sh 'kubectl delete pod -l app=frontend --ignore-not-found=true'
            }
        }
    }

    post {
        success {
            echo '🚀 프론트엔드 배포 완료! 사이트에서 확인해보세요.'
        }
        failure {
            echo '💥 에러 발생! 도움!'
        }
    }
}