pipeline {
    agent any

    environment {
        DOCKER_CRED = credentials('docker-hub-guntinue')
        IMAGE_NAME = 'guntinue/armageddon-frontend'
    }

    stages {
        // 노드 의존성 설치 및 빌드
        stage('Build Node.js') {
            steps {
                dir('frontend/armageddon') {
                    // Node.js가 젠킨스 서버에 설치되어 있어야 함
                    // 없다면 docker agent를 쓰는 방법도 있지만 일단 쉘로 진행
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        // 도커 이미지 빌드
        stage('Docker Build') {
            steps {
                dir('frontend/armageddon') {
                    // 플랫폼 명시 (Mac M1/M2 사용자를 위해 amd64 강제)
                    sh 'docker build --no-cache --platform linux/amd64 -t $IMAGE_NAME:latest .'
                }
            }
        }

        // 도커 허브 푸시
        stage('Docker Push') {
            steps {
                sh 'echo $DOCKER_CRED_PSW | docker login -u $DOCKER_CRED_USR --password-stdin'
                sh 'docker push $IMAGE_NAME:latest'
            }
        }

        // 배포
        stage('Deploy to K8s') {
            steps {
                // 프론트엔드 파드 삭제 -> 재시작
                sh 'kubectl delete pod -l app=frontend --ignore-not-found=true'
            }
        }
    }

    post {
            always {
                script {
                    if (isUnix()) {
                        sh 'docker logout'
                    } else {
                        bat 'docker logout'
                    }
                }
            }
            success {
                withCredentials([string(credentialsId: 'armageddon-discord', variable: 'DISCORD')]) {
                    discordSend(
                        description: """
                        **프론트앤드 빌드 성공!** :tada:

                        **제목**: ${currentBuild.displayName}
                        **결과**: :white_check_mark: ${currentBuild.currentResult}
                        **실행 시간**: ${currentBuild.duration / 1000}s
                        **링크**: [빌드 결과 보기](${env.BUILD_URL})
                        """,
                        title: "${env.JOB_NAME} 프론트앤드 빌드 성공!",
                        webhookURL: "$DISCORD"
                    )
                }
            }
            failure {
                withCredentials([string(credentialsId: 'armageddon-discord', variable: 'DISCORD')]) {
                    discordSend(
                        description: """
                        **프론트앤드 빌드 실패!** :x:

                        **제목**: ${currentBuild.displayName}
                        **결과**: :x: ${currentBuild.currentResult}
                        **실행 시간**: ${currentBuild.duration / 1000}s
                        **링크**: [빌드 결과 보기](${env.BUILD_URL})
                        """,
                        title: "${env.JOB_NAME} 프론트앤드 빌드 실패!",
                        webhookURL: "$DISCORD"
                    )
                }
            }
    }
}